# Generated by Django 5.1.3 on 2024-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_users_db_remove_webpage_topic_delete_accessrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_db',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users_db',
            name='first_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='users_db',
            name='last_name',
            field=models.CharField(max_length=264),
        ),
    ]
